### ISSUE TITLE
 0.3.0 release checklist

### ISSUE THREAD

**Issue by yallop** [dsheets/ocaml-unix-dirent#7]
* [x] Add a more detailed [README][README] (#9)
* [x] Review the interface for consistency and completeness (#8)
* [x] Bring the authors list up to date (99431b1)
* [x] Update the [changelog][changelog] (2808ef5)
* [x] Check the build with and without optional dependencies
* [x] Update version numbers
* [x] Tag ([0.3.0](https://github.com/dsheets/ocaml-unix-dirent/tree/0.3.0))
* [x] Publish on [opam-repository][opam-repository] (https://github.com/ocaml/opam-repository/pull/6263)

[README]: https://github.com/dsheets/ocaml-unix-dirent/blob/master/README.md
[changelog]: https://github.com/dsheets/ocaml-unix-dirent/blob/master/CHANGES
[opam-repository]: https://github.com/ocaml/opam-repository/
